# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Rajat Chakraborty 
title: Trawellblogger | Author | Entrepreneur
email: info@trawellblogging.com
# email_title: Email (Email title override)
phone: +91-777-489-8856
# phone_title: Phone (Phone title override)
website: [Pack-Ur-Bags- A Trawellblogger's Guide To Explore Life](https://trawellblogging.com)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: rajatchakks
github_username:  rajatchakraborty81
facebook_username: packurbags
instagram_username: trawellblogger
linkedin_username: rajatchaks
pinterest_username: packurbags
youtube_username: rajatchakraborty

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/IMG_20200611_132922.jpg Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  To move, to breathe, to fly, to float, to gain while all you give..
  To roam the roads of lands remote, to travel is to live!!
  Rajat is a freelance travel blogger with extensive experience of a decade plus years of traveling and
  7+ years of travel writing experience. He writes extensively on [DIY International Travel](https://trawellblogging.com/destinations/),[Travel Hacks](https://trawellblogging.com/trawell-hacks/), Destination and Stay reviews.
  
  He has authored [4 travel books](https://www.amazon.in/Rajat-Chakraborty/e/B082R7Z5WJ/)so far and worked single handedly on developing methods to use
  Airline Miles Programs with debit cards.
  
  He also runs an independent travel space on Quora - ['Trawellblogger's Guides'](https://www.quora.com/q/trawellbloggersguides) which draws more than 200,000 followers.

content:
  - title: Awards & Recognitions # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 2020
        link: https://i1.wp.com/trawellblogging.com/wp-content/uploads/2020/09/certificate-1.jpg?resize=595%2C421&ssl=1 (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Certified from Mininstry of Tourism 
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Institution name
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
